export const SCAN = "LOCATION_SCAN";
export const RECEIVE_LOCATION = "RECEIVE_LOCATION";
export const RECEIVE_ERROR = "LOCATION_RECEIVE_ERROR";
export const RECEIVE_REJECTION = "LOCATION_RECEIVE_REJECTION";
export const RENEW_STATE = "LOCATION_RENEW_STATE";
