export const SCAN = "STOCK_SCAN";
export const RECEIVE_STOCK = "RECEIVE_STOCK";
export const RECEIVE_ERROR = "LOCATION_RECEIVE_ERROR";
export const RECEIVE_REJECTION = "LOCATION_RECEIVE_REJECTION";
export const RENEW_STATE = "LOCATION_RENEW_STATE";
export const RENEW_REQUEST_STATE = "LOCATION_RENEW_REQUEST_STATE";
export const ADD_ITEM_TO_STORE = "ADD_ITEM_TO_STORE"
